[project]
name = "mokuro-online"
version = "0.0.1"
description = "Flask app to run mokuro in a dedicated server, including a API"
dependencies = [
    "mokuro",
    "Flask==2.3.3",
    "Flask-Caching==2.0.2",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
